### ISSUE TITLE
Annotate screen doesn't work VS2022

### ISSUE THREAD

**Issue by sabasjon** [AmpScm/AnkhSVN#47]
In VS 2022 - when we try and open the 'Annotate' window by right clicking on a file in Solution Explorer we are presented with an error,

<img width="738" alt="image" src="https://user-images.githubusercontent.com/11357950/167610755-bbe654d6-ced5-4a1c-bb57-7f82854c80b8.png">

If we then click OK - the window behind that is now showing

<img width="555" alt="2022-05-10_11-41-50" src="https://user-images.githubusercontent.com/11357950/167610922-fcb1c2a1-61ab-452c-aa58-81232cd6562f.png">

From then on - if we try and use Annotate again, the two errors don't appear, however the screen doesn't draw correctly,

<img width="679" alt="2022-05-10_11-43-04" src="https://user-images.githubusercontent.com/11357950/167611198-69d3ba80-320c-44c0-9fd8-426b8e6729e7.png">

I have manually blurred out the Dev name on the list of check ins on the left side, but you can see there is no code shown on the right side of the screen and then on the left there is a 'hole' where I can see through to a different .cs file that I had open in VS 2022 - i.e. the one sitting 'behind' the annotated .cs file.

I am not sure if this relates to the other Annotate window issue open below (#7) but thought I would raise a new issue with the screen shots anyway.

cheers

**Comment by mscheuringer-schauer** [comment]
Is there any progress with this issue? I have the same here with VisualStudio 2022 Version 17.2.1 and the latest nightly build of AnkhSVN.

**Comment by 00bins** [comment]
I looked at this - and have no idea why it doesn't work. I've made a bodge/workaround which invokes the tortoisesvn blame dialog/window instead if anyone is interested

**Comment by ARMoir** [comment]
@sabasjon @mscheuringer-schauer @00bins 
Can you confirm this issue is resolved in the latest build?
https://github.com/AmpScm/AnkhSVN/releases/tag/v2.9.195

**Comment by 00bins** [comment]
First off - thanks for fixing this - it's been a bugbear for so long, but ...

I made local modifications to ankh to make it use the tortoisesvn blame, and now that this is fixed I've noticed that the tortoisesvn blame has better functionality, in that it has a right-click context menu that can re-blame on a change, or show a diff. It's so long since I've been able to use ankh blame in vs that I can't remember if that menu was ever there. Can anyone else confirm?

cheers
Rob

**Comment by ARMoir** [comment]
@00bins 
You are correct, the right-click context menu was still broken in the last build. 
Can you confirm the Menu is now working as expected in the latest?
https://github.com/AmpScm/AnkhSVN/releases/tag/v2.9.199
